export const AUTH_LOADING = "AUTH_LOADING";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_UNSUCCESS = "USER_LOGIN_UNSUCCESS";
export const LOGIN_SYSTEM_ERROR = "LOGIN_SYSTEM_ERROR";
export const LOGOUT = "LOGOUT";
export const COOKIE_CHECKED = "COOKIE_CHECKED";
export const USER_LOCATION_FOUND = "USER_LOCATION_FOUND";
